version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:16.13.1
    steps:
      - checkout
      - run:
          name: Install Deps
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test
      - run:
          name: Generate Reports
          command: |
            npm run report
workflows:
  execute_tests:
    jobs:
      - run_tests